### ISSUE TITLE
in multiline selections the end column can't be smaller than the start column

### ISSUE THREAD

**Issue by eMBee** [lxsang/PTerm#14]
if i want to select this:

```
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxXXXXXXXXXXXXXX
XXXXXXXXXXXXXXxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```
the selection becomes:
```
xxxxxxxxxxxxxxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxxxxxxxxxxxxxx
```
the end column in the second line is set to be equal to the column where i first clicked to begin the selection in the first line. the beginning column in the first line changed to be equal to the column where i release the cursor in the second line.

**Comment by lxsang** [comment]
fixed.
This one is a little bit tricky due to how Pharo handle a rectangle (a pair of points)
