### ISSUE TITLE
enhancement: don't hide the scrollbar when the mouse leaves the window

### ISSUE THREAD

**Issue by eMBee** [lxsang/PTerm#15]
since the terminal is mostly used with the keyboard, the position of the mouse should have no effect on the window. 

hiding the scrollbar also does not enable more space. but instead it gives the impression that text in the terminal does not go to the end of the line:

```
┌─────────────────────────────┐
│zxfvasdlfvgbasdlfgasdfg     █│
│fthsdrtyhjsdrthsryhsrthsrtyh█│
│                            █│
└─────────────────────────────┘
┌─────────────────────────────┐
│zxfvasdlfvgbasdlfgasdfg      │
│fthsdrtyhjsdrthsryhsrthsrtyh │
│                             │
└─────────────────────────────┘
```
with the scrollbar, the second line text goes right to the edge.
without the scrollbar, it looks like there is a space at the end of the second line.

this can give the appearance of improperly formatted output in some applications.

**Comment by lxsang** [comment]
fixed
