### ISSUE TITLE
SubscriptOutOfBounds error on selection.

### ISSUE THREAD

**Issue by eMBee** [lxsang/PTerm#16]
under certain conditions (and i haven't figured out a pattern yet) making a selection from the first column triggers a SubscriptOutOfBounds error. once that error is triggered, the terminal continues to work, but selection anywhere is no longer possible. it is necessary to close the terminal and open a new one.

thanks to tmux this is just a mere nuisance and doesn't lead to dataloss for me.

**Comment by lxsang** [comment]
I have this problem too, but don't  know how to reproduce it yet
