### ISSUE TITLE
How to catch the current command? 

### ISSUE THREAD

**Issue by hogoww** [lxsang/PTerm#19]
Hi,
This is not an issue per se, I'm just trying to see if I have (or may have) a buffer containing the current command. 
My aim is instantiate a terminal emulator to run commands more easily from pharo.
Thanks in advance :)
Pierre

**Comment by lxsang** [comment]
Hi, I'm not sure that i can understand you correctly.
What exactly the buffer that you want ? If you just want to execute and get its result into a buffer, you may consider using [https://github.com/pharo-contributions/OSSubprocess](OSSubprocess).

PTerm, on the other hand, allows you have an entire Terminal Emulator inside the Pharo IDE

**Comment by hogoww** [comment]
Hi,
I tried that, but I had trouble getting the command results back.
this seemed easier to do with your work.
Did I just miss part of the documentation? 
I don't know if that's clearer but I would like to have a like to a terminal emulator (manage event ect..)

**Comment by lxsang** [comment]
I have a similar project to OSSubprocess: [SystemProcess](https://github.com/lxsang/SystemProcess). You can try it out.
I'm not sure if it fulfill your requirement but i can help you resolve all the problems related to SystemProcess.

**Comment by hogoww** [comment]
Hi, I send you a private mail (through your blog) to stop making noise here.
I do not know if you got it (global current situation may prevent you to, of course !) but just in case, let me try to sum it up here! =)
I would like to be able to just have something like:
Terminal sendLine:'ls'
Which would give me a string with the result.

Also, I'd like to be able to use this with interactive program, such as clisp, python, and whatever else, which prevents the use of SystemProcess/OSSubProcess (UNLESS I misunderstood them when I used it)

Thank you !

**Comment by lxsang** [comment]
Hello, i responded to your private message on my blog, but it seams that there is a problem with your email address so the message is undelivered <pierre.misse-chanabier@inria.com> (connection time out). So i put it here, for further communication please contact me at xsang.le@gmail.com

```
Hi,

With PTerm, you can do any of the stuffs that you mentioned (emacs, CLips, etc).
What PTerm do is, it fist opens a shell session in a separated process, then redirect STDIO of this process to Pharo. In this way, Pharo can provide a GUI interface (Terminal Emulator) to handle input and output of that process (shell session).

It looks like PTerm is what you want, instead of doing in on your own, i suggest to fork PTerm into your local repository and modify it to your need.

Feel free to ask any question related to PTerm, i will try to help you if i can.

Regards,

Sang
```

**Comment by lxsang** [comment]
Please consider close this issue and switch to private communication using email. 
Regards,

**Comment by hogoww** [comment]
Thanks !
