### ISSUE TITLE
Allow to open another shell than bash

### ISSUE THREAD

**Issue by juliendelplanque** [lxsang/PTerm#2]
I was able to make your project work using zsh by modifying:
```
TerminalEmulator class>>#openBash
	
	| win term |
	term := (PTerm new xspawn: { '/bin/zsh'. '-i'} env: self environ ).
	"term := (PTermEcho new)."
	win := self open.
	term asProtocolStack
		push: TerminalEmulatorXterm new;
		push: win tty;
		install;
		run.
	win extent: win extent.
	^ win	
```

Maybe this method should be generalised like `#openShell:` when one can provide the path to the terminal to use.

<img width="974" alt="capture d ecran 2018-10-20 a 14 16 21" src="https://user-images.githubusercontent.com/8260456/47255519-c4ec9780-d472-11e8-9674-684f7d585bf3.png">

This is really cool because except for the prompt, all my zsh config seems to work (completion, etc). Thank you for your work!

**Comment by lxsang** [comment]
Good idea, theoretically, PTerm can spawn any shell (sh, bash, zsh...) or command available in the system. I will add the #openShell: method as you suggest. Thanks
