### ISSUE TITLE
P9 Can't Find Library

### ISSUE THREAD

**Issue by seandenigris** [lxsang/PTerm#20]
I started to port to P9. I had it mostly working, but now in P9 with latest VM (from yesterday), FFI fails to find the library. I return a full path from `#ffiLibraryName`. 

I asked on Pharo Discord for a pointer as to what other causes there may be? My WIP port is here: https://github.com/seandenigris/PTerm/tree/port_p9

**Comment by lxsang** [comment]
Hello, AFAIK FFI API on Pharo 9 is not backward compatible with Pharo 7, so the FFI part should be modified to be compatible with P9.

Note that at the first run PTerm will try to compile a small C helper library from source code with GCC. This library allows open a fully interactive shell from Pharo.

I've always wanted to port Pterm to P9, i may take a look at your port when i have free time.

**Comment by seandenigris** [comment]
Thanks for the reply. I'm sure I had it working, but I changed from the x64 to arm vm and then there was an updated vm the other day, and I can't remember the magic combination. 

Maybe one of the VM/FFI gurus can give us a pointer on how to debug cc @tesonep @guillep @estebanlm

**Comment by lxsang** [comment]
There is several points: 
- Do you have GCC on your ARM system that run Pterm?
- If yes, the option -m32 and -m64 used to build the C helper library may not be available on arm-gcc, you shoud try to change these options

**Comment by seandenigris** [comment]
FYI Everything works on arm M1 in a P8 image, but not sure how Rosetta affects things

**Comment by Rinzwind** [comment]
@seandenigris could you test whether you still have this issue when using the ‘pharo9-keyboard-mouse-events’ branch?

```smalltalk
Metacello new
	repository: 'github://lxsang/PTerm:pharo9-keyboard-mouse-events';
	baseline: 'PTerm';
	load
```

Alternatively, you could use https://github.com/Yesplan/PTerm/commit/630ef95ba65f which is just a trial merge of the ‘pharo9-keyboard-mouse-events’ and ‘master’ branches: `repository: 'github://Yesplan/PTerm:630ef95ba65f0a95a94e43c300ac5c9be580d214';`.

You may want to put a breakpoint or ‘Halt signal’ in the Error-handling block in `PTerm>>#xspawn:env:` to check whether the fallback is used:

https://github.com/lxsang/PTerm/blob/2d842b522c8626ae215f7da765f745da31781466/PTerm-Core/PTerm.class.st#L229-L233

If the fallback is used, Bash will report ‘no job control’ (as discussed in @lxsang’s blog post at https://blog.lxsang.me/post/id/24):

<img width="366" alt="PTerm Bash No Job Control" src="https://user-images.githubusercontent.com/1611248/180595445-52517448-e995-4178-8d4b-7d493efd0f66.png">

**Comment by seandenigris** [comment]
> @seandenigris could you test whether you still have this issue when using the ‘pharo9-keyboard-mouse-events’ branch?

It works!

There was a DNU `#openModal:` in `TerminalEmulator class>>#selecFont` from:
```smalltalk
UITheme builder openModal: fontSelector.
```
which I replaced with:
```smalltalk
fontSelector openModal
```

I would advise removing this modal dialog completely from the installation process - just set to a reasonable default if possible. It's too disruptive, especially in the case of CI and other automated workflows.

But other than that, everything is working. I'm really excited about using this. Thanks :)

**Comment by seandenigris** [comment]
Also works in P10, but font choosing is even more broken because apparently the Freetype Window class no longer exists. Once the font is set manually, it seems to work well though!

**Comment by lxsang** [comment]
@seandenigris @Rinzwind a fix for the Font selection problem on Pharo9 and Pharo10 is available on this branch [ui-fix-font-selector](https://github.com/lxsang/PTerm/tree/ui-fix-font-selector).

I'm not realy happy with that fix but at least, it  does the job

**Comment by Rinzwind** [comment]
@lxsang I took a look at the branch in PR https://github.com/lxsang/PTerm/pull/46.

As suggested by @seandenigris, it might be better to drop the `#checkFont` from the `#postLoadDoIt`:

https://github.com/lxsang/PTerm/blob/b8dd2451421a3ccb7e00fd49ffa1ac772cbf1f61/BaselineOfPTerm/BaselineOfPTerm.class.st#L12

If one does not already have the font ‘DejaVu Sans Mono’, loading PTerm while using `--headless` hangs:

```bash
"${pharovm}" --headless "${pharoimage}" eval \
  "Metacello new repository: 'github://lxsang/PTerm:ui-fix-font-selector'; baseline: 'PTerm'; load"
```

**Comment by seandenigris** [comment]
Seems to be fixed and I see there’s another issue for the front checking so I’ll close. Thanks!
