### ISSUE TITLE
Terminal windows are closed when reopening Pharo image

### ISSUE THREAD

**Issue by Rinzwind** [lxsang/PTerm#29]
Currently, if you save a Pharo image with Terminal windows open, those windows are closed when the Pharo image is reopened and you cannot see what was in those windows.

Suggestions for improvement that were made in pull request #26:

* Do not close the Terminal windows automatically when reopening the Pharo image
* Provide a way to restore the session of a Terminal window (similar to what macOS’s Terminal does)

**Comment by lxsang** [comment]
An advantage of Pharo is that a saved image preserves the state of all current opened windows. Terminal sessions can be attached to the window states and can be saved without the need of an external session file (like in MacOS).
