### ISSUE TITLE
Pressing ‘Return’ or ‘CTRL-D’ does not work in Pharo 9

### ISSUE THREAD

**Issue by Rinzwind** [lxsang/PTerm#31]
When using Terminal in Pharo 9 (requires: PR #30), pressing CTRL-D to exit Bash, or RETURN to execute a command does not work.

**Comment by Rinzwind** [comment]
@seandenigris posted another issue about this with more info: https://github.com/pharo-project/pharo/issues/10729

**Comment by lxsang** [comment]
In pharo 9 and up, some keys such as non printable characters or meta/control keys are not handled by #keystroke event. Instead they are catched by #keyDown event.  I propose a solution in PR #34.

@Rinzwind Could you take a look?

Thanks

**Comment by lxsang** [comment]
I took a quick test, look like it also works with Pharo10
