### ISSUE TITLE
enhancement: light or dark mode should align with pharo color scheme

### ISSUE THREAD

**Issue by eMBee** [lxsang/PTerm#5]
instead of picking its own default, pterm should use the mode that pharo itself uses. if the pharo color scheme is light, the terminal should be light, and if it is dark, the terminal should be dark too. (preferable in just the same colors. (dark grey instead of dark green) though i can see the appeal of a green terminal too. (i use the light theme myself so that's just a thought))

**Comment by lxsang** [comment]
I would not rely on the Pharo theme, because PTerm has its own theme system, users now can change the default theme for PTerm via the window menu. Various themes are available, and more to come in future update

**Comment by eMBee** [comment]
themes look very nice! 
i'd still like the default light/dark choice to be aligned with the pharo theme. 
but that's really a minor issue now.
