### ISSUE TITLE
enhancement: font configurator

### ISSUE THREAD

**Issue by eMBee** [lxsang/PTerm#6]
this is not an important feature, but i submit it because if implemented, it could replace some of the current fonthandling code.

with a font configurator, it would be sufficient to use any already available monospace font as default, and leave any special font handling to the user, who would either select from available fonts or install their own, just like they would for pharo as a whole.

**Comment by eMBee** [comment]
this looks very good. font switching works. 

minor issues: 

* the font selection dialog always opens up with source sans pro selected, no matter which font is actually in use. (for one that means that one can't go there to see which current font is loaded)

* if i open the dialog, and then cancel, the font always resets to source code pro instead of keeping the currently selected font.

try this: open the font dialog, don't change the selection, hit ok -> font changes to non-monospace source sans pro.
open the dialog again, don't change the selection, and this time hit cancel -> font changes to the monospace font source code pro.

* finally, i can't see if the loading of unifont actually works. it seems to do nothing.

**Comment by lxsang** [comment]
Ok i'll take a look of that issue

**Comment by lxsang** [comment]
This issue is fixed in the new update

**Comment by eMBee** [comment]
i can confirm that it works nicely now, great work! thanks.
