### ISSUE TITLE
Function keys are not supported

### ISSUE THREAD

**Issue by Rinzwind** [lxsang/PTerm#60]
Function keys are not yet supported in PTerm. Some applications that use them are [GNU Midnight Commander](https://en.wikipedia.org/w/index.php?title=Midnight_Commander&oldid=1172107975) and [htop](https://en.wikipedia.org/w/index.php?title=Htop&oldid=1172103987).

**Comment by Rinzwind** [comment]
While trying to implement support for function keys, I encountered a slight problem: TerminalEmulatorXterm nominally mimics xterm, but [TerminalEmulator’s `#environ`](https://github.com/lxsang/PTerm/blob/4d1a720adf9932c8a0ffbadcf78451d5711d3ca5/PTerm-UI/TerminalEmulator.class.st#L72-L81) actually sets the ‘TERM’ environment variable to ‘linux’, and these two terminals use different sequences for some of the function keys. The sequences for each can be gotten from ‘tput’ through the following snippet:

```smalltalk
#(xterm linux)
	collect: [ :type |
		type -> ((1 to: 24)
			collect: [ :n |
				(KeyboardKey named: ('F{1}' format: { n })) ->
					(LibC resultOfCommand: ('tput -T {1} kf{2}' format: { type. n })) ]
			as: OrderedDictionary) ]
	as: OrderedDictionary
```

**Comment by lxsang** [comment]
Yes i remember settting TERM to `linux` for some reason (can't recall which one though, probably something related to the themes).

We could change it to `xterm` or `xterm-256color`, but need to check for any side effects
