### ISSUE TITLE
enhancement: send ctrl-w, pgup and pgdown into the terminal

### ISSUE THREAD

**Issue by eMBee** [lxsang/PTerm#8]
ctrl-w is used in pharo to close windows. but in the terminal that conflicts with commanline applications such as vim and others that want to use ctrl-w for themselves.

i believe that being able to close the terminal with ctrl-w is less important that supporting commandline applications that need this keyboard shortcut.

if one does want to close a terminal window, typing exit within the shell will also work, and is in fact the safer (and faster, because it skips the close prompt) option. 

for the rare case that the shell is locked up somehow, using the mouse to close the window should be acceptable.

same goes for pgup and pgdown. i think it would be beneficial to support commandline applications running inside the terminal first.

**Comment by lxsang** [comment]
ctrl-w/ctrl-u issues are fixed by hacking to the keymap system of pharo (in the last update).

PgUp, and pgDown are recognized by PTerm, but somehow, the actions are not performed as expected. I'll investigate this WE.

**Comment by eMBee** [comment]
thanks. they work nicely. this cleared the last place where needed that backup terminal. for any remaining issues so far i have been able to find workarounds without switching terminals.

**Comment by lxsang** [comment]
**page down/ page up/ home/ fin**: work as expected inside applications like nano, vi
from the terminal prompt: **shift + page up/ shift + page** down are used to scroll the scroll bar
